apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
        - name: assignment-4
          image: jp.icr.io/shrruthi/assignment_4
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              protocol: TCP